"""
Lgm_CTrans module, this contains the necessary code for coordinate
transformations in Lgm

the ugly top part is
Generated by h2py from ../libLanlGeoMag/Lgm/Lgm_CTrans.h
@todo: go through and remove the bits we don't need

@author: Brian Larsen
@organization: LANL
@contact: balarsen@lanl.gov

@version: V1: 20-Dec-2010 (BAL)
"""

from __future__ import division

import numpy

import Lgm_Vector

from Lgm_Wrap import Lgm_CTrans

class Lgm_CTrans(Lgm_CTrans):
    def __init__(self):
        self.nNutationTerms = 106;

         #
         #  Initialize Earth Orientation Parameters to defaults They can be
         #  over-ridden later with actual values.  This allows users to use the
         #  less accurate defaults if EOP data is unavailable or not
         #  needed/desired.
         #
        self.DUT1  = 0.0# ; // seconds
        self.xp    = 0.0#; // radians
        self.yp    = 0.0#; // radians
        self.ddPsi = 0.0#; // radians
        self.ddEps = 0.0#; // radians

def dateToDateLong(inval):
    """
    convert a python date or datetime object to a Date (long) object that
    LanlGeoMag Likes to use

    @author: Brian Larsen
    @organization: LANL
    @contact: balarsen@lanl.gov

    @version: V1: 04-Jan-2011 (BAL)
    """
    try:
        if len(inval) > 1:
            if isinstance(inval, numpy.ndarray):
                return numpy.array([long(val.strftime('%Y%m%d')) for val in inval])
            else:
                return [long(val.strftime('%Y%m%d')) for val in inval]
    except:
        return long(inval.strftime('%Y%m%d'))

def dateToFPHours(inval):
    """
    convert a python datetime object to a Floating point hours (double) object that
    LanlGeoMag Likes to use

    @author: Brian Larsen
    @organization: LANL
    @contact: balarsen@lanl.gov

    @version: V1: 06-Jan-2011 (BAL)
    """
    try:
        if len(inval) > 1:
            lst = [val.hour + val.minute/60 +
                                    val.second/60/60 +
                                    val.microsecond/60/60/1000000 for val in inval]
            if isinstance(inval, numpy.ndarray):
                return numpy.array(lst)
            else:
                return lst
    except:
        return inval.hour + inval.minute/60 + \
                                    inval.second/60/60 + \
                                    inval.microsecond/60/60/1000000



