"""
Lgm_MagModelInfo module, this contains the necessary code Mag Model Info

the ugly top part is
Generated by h2py from ../libLanlGeoMag/Lgm/Lgm_MagModelInfo.h
@todo: go through and remove the bits we don't need

@author: Brian Larsen
@organization: LANL
@contact: balarsen@lanl.gov

@version: V1: 20-Dec-2010 (BAL)
"""
from ctypes import pointer

from Lgm_Wrap import Lgm_MagModelInfo, LGM_IGRF, Lgm_CTrans, TRUE, FALSE, \
    Lgm_Set_Open_Limits, LGM_ABSOLUTE_JUMP_METHOD, DQAGS, DQAGP


class Lgm_MagModelInfo(Lgm_MagModelInfo):
    """
    LanlGeoMag class for holing Mag Model infor needed by all models

    @author: Brian Larsen
    @organization: LANL
    @contact: balarsen@lanl.gov

    @version: V1: 22-Dec-2010 (BAL)
    """
    def __init__(self):
        """
        Set the default values from Lgm
        """
        self.InternalModel = LGM_IGRF
        c_tmp = Lgm_CTrans()
        self.c     = pointer(c_tmp)
        self.Kp    = 5
        self.P     = 2.1 # SW pressure in nPa
        self.nFunc = 0
        self.B0    = 1.00   # Should nominally be 1.0 See page 30 of Schultz and Lanzerotti, [1974]
        self.B1    = 0.8100 # See page 30 of Schultz and Lanzerotti, [1974]
        self.B2    = 0.4065 # See page 30 of Schultz and Lanzerotti, [1974]
        self.SavePoints = 0
        self.Hmax       = 1.0

        self.UseInterpRoutines = TRUE
        Lgm_Set_Open_Limits( pointer(self), -80.0, 30.0, -40.0, 40.0, -40.0, 40.0 )
        self.Lgm_I_integrand_JumpMethod = LGM_ABSOLUTE_JUMP_METHOD
        #
        #  Some inits for MagStep
        #
        self.Lgm_MagStep_FirstTimeThrough = TRUE
        self.Lgm_MagStep_eps_old          = -1.0
        #
        # Set some default tolerances
        #
        self.Lgm_MagFlux_Integrator_epsabs = 0.0
        self.Lgm_MagFlux_Integrator_epsrel = 1e-5

        self.Lgm_LambdaIntegral_Integrator_epsabs = 0.0
        self.Lgm_LambdaIntegral_Integrator_epsrel = 1e-3

        self.Lgm_I_Integrator_epsrel = 0.0
        self.Lgm_I_Integrator_epsabs = 1e-3
        self.Lgm_I_Integrator = DQAGS

        self.Lgm_Sb_Integrator_epsrel = 0.0
        self.Lgm_Sb_Integrator_epsabs = 1e-3
        self.Lgm_Sb_Integrator = DQAGP # not changeable (yet...)

        self.Lgm_FindBmRadius_Tol = 1e-10
        self.Lgm_FindShellLine_I_Tol = 1e-3
        self.Lgm_TraceToMirrorPoint_Tol = 1e-7

        #
        # Bounce Loss Cone Height
        #
        self.Lgm_LossConeHeight = 100.0 # km above the Earth Ellipsoid.

        #
        # Inits for OP77
        #
        self.OP77_TILTL = 99.0
