"""
Lgm_LeapSeconds module, this contains the necessary code Leap Seconds

the ugly top part is
Generated by h2py from ../libLanlGeoMag/Lgm/Lgm_LeapSeconds.h
@todo: go through and remove the bits we don't need

@author: Brian Larsen
@organization: LANL
@contact: balarsen@lanl.gov

@version: V1: 20-Dec-2010 (BAL)
"""


###############################################################################
###############################################################################
###############################################################################

def STRINGIFY(x): return #x

def EXPAND(x): return STRINGIFY(x)
# Included from stdio.h

# Included from _types.h

# Included from sys/_types.h

# Included from sys/cdefs.h
def __P(protos): return protos

def __STRING(x): return #x

def __P(protos): return ()

def __STRING(x): return "x"

def __attribute__(x): return

def __COPYRIGHT(s): return __IDSTRING(copyright,s)

def __RCSID(s): return __IDSTRING(rcsid,s)

def __SCCSID(s): return __IDSTRING(sccsid,s)

def __PROJECT_VERSION(s): return __IDSTRING(project_version,s)

__DARWIN_ONLY_64_BIT_INO_T = 0
__DARWIN_ONLY_VERS_1050 = 0
__DARWIN_ONLY_UNIX_CONFORMANCE = 1
__DARWIN_ONLY_UNIX_CONFORMANCE = 0
__DARWIN_UNIX03 = 1
__DARWIN_UNIX03 = 1
__DARWIN_UNIX03 = 0
__DARWIN_UNIX03 = 0
__DARWIN_UNIX03 = 1
__DARWIN_64_BIT_INO_T = 1
__DARWIN_64_BIT_INO_T = 0
__DARWIN_64_BIT_INO_T = 1
__DARWIN_64_BIT_INO_T = 0
__DARWIN_64_BIT_INO_T = 1
__DARWIN_VERS_1050 = 1
__DARWIN_VERS_1050 = 0
__DARWIN_VERS_1050 = 1
__DARWIN_NON_CANCELABLE = 0
__DARWIN_SUF_UNIX03 = "$UNIX2003"
__DARWIN_SUF_64_BIT_INO_T = "$INODE64"
__DARWIN_SUF_1050 = "$1050"
__DARWIN_SUF_NON_CANCELABLE = "$NOCANCEL"
__DARWIN_SUF_EXTSN = "$DARWIN_EXTSN"
def __DARWIN_10_6_AND_LATER_ALIAS(x): return

def __DARWIN_10_6_AND_LATER_ALIAS(x): return x

_POSIX_C_SOURCE = 199009L
_POSIX_C_SOURCE = 199209L
_POSIX_C_SOURCE = 200112L
_POSIX_C_SOURCE = 199506L
_POSIX_C_SOURCE = 198808L
def __DARWIN_LDBL_COMPAT(x): return

def __DARWIN_LDBL_COMPAT2(x): return

__DARWIN_LONG_DOUBLE_IS_DOUBLE = 1
__DARWIN_LONG_DOUBLE_IS_DOUBLE = 0
def __DARWIN_LDBL_COMPAT(x): return

def __DARWIN_LDBL_COMPAT2(x): return

__DARWIN_LONG_DOUBLE_IS_DOUBLE = 1
def __DARWIN_LDBL_COMPAT(x): return

def __DARWIN_LDBL_COMPAT2(x): return

__DARWIN_LONG_DOUBLE_IS_DOUBLE = 0
_DARWIN_FEATURE_64_BIT_INODE = 1
_DARWIN_FEATURE_LONG_DOUBLE_IS_DOUBLE = 1
_DARWIN_FEATURE_ONLY_64_BIT_INODE = 1
_DARWIN_FEATURE_ONLY_VERS_1050 = 1
_DARWIN_FEATURE_ONLY_UNIX_CONFORMANCE = 1
_DARWIN_FEATURE_UNIX_CONFORMANCE = 3

# Included from machine/_types.h
__PTHREAD_SIZE__ = 1168
__PTHREAD_ATTR_SIZE__ = 56
__PTHREAD_MUTEXATTR_SIZE__ = 8
__PTHREAD_MUTEX_SIZE__ = 56
__PTHREAD_CONDATTR_SIZE__ = 8
__PTHREAD_COND_SIZE__ = 40
__PTHREAD_ONCE_SIZE__ = 8
__PTHREAD_RWLOCK_SIZE__ = 192
__PTHREAD_RWLOCKATTR_SIZE__ = 16
__PTHREAD_SIZE__ = 596
__PTHREAD_ATTR_SIZE__ = 36
__PTHREAD_MUTEXATTR_SIZE__ = 8
__PTHREAD_MUTEX_SIZE__ = 40
__PTHREAD_CONDATTR_SIZE__ = 4
__PTHREAD_COND_SIZE__ = 24
__PTHREAD_ONCE_SIZE__ = 4
__PTHREAD_RWLOCK_SIZE__ = 124
__PTHREAD_RWLOCKATTR_SIZE__ = 12
__DARWIN_NULL = (0L)
__DARWIN_NULL = 0
def __strftimelike(fmtarg): return \

__DARWIN_WCHAR_MAX = 0x7fffffff
__DARWIN_WCHAR_MIN = (-0x7fffffff - 1)
__DARWIN_WCHAR_MIN = 0
_FORTIFY_SOURCE = 0
_FORTIFY_SOURCE = 2
NULL = __DARWIN_NULL
__SLBF = 0x0001
__SNBF = 0x0002
__SRD = 0x0004
__SWR = 0x0008
__SRW = 0x0010
__SEOF = 0x0020
__SERR = 0x0040
__SMBF = 0x0080
__SAPP = 0x0100
__SSTR = 0x0200
__SOPT = 0x0400
__SNPT = 0x0800
__SOFF = 0x1000
__SMOD = 0x2000
__SALC = 0x4000
__SIGN = 0x8000
_IOFBF = 0
_IOLBF = 1
_IONBF = 2
BUFSIZ = 1024
EOF = (-1)
FOPEN_MAX = 20
FILENAME_MAX = 1024
P_tmpdir = "/var/tmp/"
L_tmpnam = 1024
TMP_MAX = 308915776
SEEK_SET = 0
SEEK_CUR = 1
SEEK_END = 2
L_ctermid = 1024
def feof_unlocked(p): return __sfeof(p)

def ferror_unlocked(p): return __sferror(p)

def clearerr_unlocked(p): return __sclearerr(p)

def fileno_unlocked(p): return __sfileno(p)

def getc_unlocked(fp): return __sgetc(fp)

def putchar_unlocked(x): return putc_unlocked(x, stdout)


# Included from xlocale/_stdio.h

# Included from secure/_stdio.h

# Included from secure/_common.h
_USE_FORTIFY_LEVEL = 2
_USE_FORTIFY_LEVEL = 1
_USE_FORTIFY_LEVEL = 0
def __darwin_obsz0(object): return __builtin_object_size (object, 0)

def __darwin_obsz(object): return __builtin_object_size (object, _USE_FORTIFY_LEVEL > 1)


# Included from stdlib.h

# Included from Availability.h
__MAC_10_0 = 1000
__MAC_10_1 = 1010
__MAC_10_2 = 1020
__MAC_10_3 = 1030
__MAC_10_4 = 1040
__MAC_10_5 = 1050
__MAC_10_6 = 1060
__MAC_NA = 9999
__IPHONE_2_0 = 20000
__IPHONE_2_1 = 20100
__IPHONE_2_2 = 20200
__IPHONE_3_0 = 30000
__IPHONE_NA = 99999

# Included from AvailabilityInternal.h
__IPHONE_OS_VERSION_MAX_ALLOWED = __IPHONE_3_0
__IPHONE_OS_VERSION_MIN_REQUIRED = __IPHONE_2_0
__MAC_OS_X_VERSION_MAX_ALLOWED = __MAC_10_6

# Included from sys/wait.h

# Included from sys/signal.h

# Included from sys/appleapiopts.h
__DARWIN_NSIG = 32
NSIG = __DARWIN_NSIG

# Included from machine/signal.h
SIGHUP = 1
SIGINT = 2
SIGQUIT = 3
SIGILL = 4
SIGTRAP = 5
SIGABRT = 6
SIGPOLL = 7
SIGIOT = SIGABRT
SIGEMT = 7
SIGFPE = 8
SIGKILL = 9
SIGBUS = 10
SIGSEGV = 11
SIGSYS = 12
SIGPIPE = 13
SIGALRM = 14
SIGTERM = 15
SIGURG = 16
SIGSTOP = 17
SIGTSTP = 18
SIGCONT = 19
SIGCHLD = 20
SIGTTIN = 21
SIGTTOU = 22
SIGIO = 23
SIGXCPU = 24
SIGXFSZ = 25
SIGVTALRM = 26
SIGPROF = 27
SIGWINCH = 28
SIGINFO = 29
SIGUSR1 = 30
SIGUSR2 = 31

# Included from sys/_structs.h

# Included from machine/_structs.h
__DARWIN_FD_SETSIZE = 1024
__DARWIN_NBBY = 8
def __DARWIN_FD_ZERO(p): return __builtin_bzero(p, sizeof(*(p)))

def __DARWIN_FD_ZERO(p): return bzero(p, sizeof(*(p)))

SIGEV_NONE = 0
SIGEV_SIGNAL = 1
SIGEV_THREAD = 3
ILL_NOOP = 0
ILL_ILLOPC = 1
ILL_ILLTRP = 2
ILL_PRVOPC = 3
ILL_ILLOPN = 4
ILL_ILLADR = 5
ILL_PRVREG = 6
ILL_COPROC = 7
ILL_BADSTK = 8
FPE_NOOP = 0
FPE_FLTDIV = 1
FPE_FLTOVF = 2
FPE_FLTUND = 3
FPE_FLTRES = 4
FPE_FLTINV = 5
FPE_FLTSUB = 6
FPE_INTDIV = 7
FPE_INTOVF = 8
SEGV_NOOP = 0
SEGV_MAPERR = 1
SEGV_ACCERR = 2
BUS_NOOP = 0
BUS_ADRALN = 1
BUS_ADRERR = 2
BUS_OBJERR = 3
TRAP_BRKPT = 1
TRAP_TRACE = 2
CLD_NOOP = 0
CLD_EXITED = 1
CLD_KILLED = 2
CLD_DUMPED = 3
CLD_TRAPPED = 4
CLD_STOPPED = 5
CLD_CONTINUED = 6
POLL_IN = 1
POLL_OUT = 2
POLL_MSG = 3
POLL_ERR = 4
POLL_PRI = 5
POLL_HUP = 6
SA_ONSTACK = 0x0001
SA_RESTART = 0x0002
SA_RESETHAND = 0x0004
SA_NOCLDSTOP = 0x0008
SA_NODEFER = 0x0010
SA_NOCLDWAIT = 0x0020
SA_SIGINFO = 0x0040
SA_USERTRAMP = 0x0100
SA_64REGSET = 0x0200
SA_USERSPACE_MASK = (SA_ONSTACK | SA_RESTART | SA_RESETHAND | SA_NOCLDSTOP | SA_NODEFER | SA_NOCLDWAIT | SA_SIGINFO)
SIG_BLOCK = 1
SIG_UNBLOCK = 2
SIG_SETMASK = 3
SI_USER = 0x10001
SI_QUEUE = 0x10002
SI_TIMER = 0x10003
SI_ASYNCIO = 0x10004
SI_MESGQ = 0x10005
SS_ONSTACK = 0x0001
SS_DISABLE = 0x0004
MINSIGSTKSZ = 32768
SIGSTKSZ = 131072
SV_ONSTACK = SA_ONSTACK
SV_INTERRUPT = SA_RESTART
SV_RESETHAND = SA_RESETHAND
SV_NODEFER = SA_NODEFER
SV_NOCLDSTOP = SA_NOCLDSTOP
SV_SIGINFO = SA_SIGINFO
def sigmask(m): return (1 << ((m)-1))


# Included from sys/resource.h
PRIO_PROCESS = 0
PRIO_PGRP = 1
PRIO_USER = 2
PRIO_DARWIN_THREAD = 3
PRIO_MIN = -20
PRIO_MAX = 20
PRIO_DARWIN_BG = 0x1000
RUSAGE_SELF = 0
RUSAGE_CHILDREN = -1
RLIMIT_CPU = 0
RLIMIT_FSIZE = 1
RLIMIT_DATA = 2
RLIMIT_STACK = 3
RLIMIT_CORE = 4
RLIMIT_AS = 5
RLIMIT_RSS = RLIMIT_AS
RLIMIT_MEMLOCK = 6
RLIMIT_NPROC = 7
RLIMIT_NOFILE = 8
RLIM_NLIMITS = 9
_RLIMIT_POSIX_FLAG = 0x1000
IOPOL_TYPE_DISK = 0
IOPOL_SCOPE_PROCESS = 0
IOPOL_SCOPE_THREAD = 1
IOPOL_DEFAULT = 0
IOPOL_NORMAL = 1
IOPOL_PASSIVE = 2
IOPOL_THROTTLE = 3
WNOHANG = 0x00000001
WUNTRACED = 0x00000002
def _W_INT(i): return (i)

WCOREFLAG = 0200
def _WSTATUS(x): return (_W_INT(x) & 0177)

_WSTOPPED = 0177
def WEXITSTATUS(x): return ((_W_INT(x) >> 8) & 0x000000ff)

def WEXITSTATUS(x): return (_W_INT(x) >> 8)

def WSTOPSIG(x): return (_W_INT(x) >> 8)

def WIFEXITED(x): return (_WSTATUS(x) == 0)

def WTERMSIG(x): return (_WSTATUS(x))

def WCOREDUMP(x): return (_W_INT(x) & WCOREFLAG)

def W_STOPCODE(sig): return ((sig) << 8 | _WSTOPPED)

WEXITED = 0x00000004
WSTOPPED = 0x00000008
WCONTINUED = 0x00000010
WNOWAIT = 0x00000020
WAIT_ANY = (-1)
WAIT_MYPGRP = 0

# Included from machine/endian.h
WSTOPPED = _WSTOPPED

# Included from alloca.h
def alloca(size): return __alloca(size)

def __alloca(size): return __builtin_alloca(size)

NULL = __DARWIN_NULL
EXIT_FAILURE = 1
EXIT_SUCCESS = 0
RAND_MAX = 0x7fffffff

# Included from _xlocale.h
def MB_CUR_MAX_L(x): return (___mb_cur_max_l(x))

def MB_CUR_MAX_L(x): return (___mb_cur_max_l(x))


# Included from machine/types.h

# Included from xlocale/_stdlib.h

# Included from string.h
NULL = __DARWIN_NULL

# Included from xlocale/_string.h

# Included from secure/_string.h

# Included from math.h
FALSE = 0
TRUE = 1


###############################################################################
###############################################################################
###############################################################################

import ctypes
from Lgm_Types import *



class Lgm_LeapSeconds(ctypes.Structure):
    _fields_ = [ ("nLeapSecondDates", LgmInt), # Number of leap second dates.
        ("LeapSecondDates", ctypes.POINTER(LgmLong)), # Array for holdin the Dates on which leap
                                     # seconds were added
        ("LeapSecondJDs", ctypes.POINTER(LgmDouble)), # Array for holdin the Julian Dates on
                                     # which leap seconds were added
        ("LeapSeconds", ctypes.POINTER(LgmDouble)) ] # The actual number of leap seconds that
                                     # went into effect on the given date

Lgm_LeapSecondsP = ctypes.POINTER(Lgm_LeapSeconds)

