"""
Lgm_MagModelInfo module, this contains the necessary code Mag Model Info

the ugly top part is
Generated by h2py from ../libLanlGeoMag/Lgm/Lgm_MagModelInfo.h
@todo: go through and remove the bits we don't need

@author: Brian Larsen
@organization: LANL
@contact: balarsen@lanl.gov

@version: V1: 20-Dec-2010 (BAL)
"""
from ctypes import pointer

from Lgm_Wrap import Lgm_MagEphemInfo, Lgm_InitMagEphemInfoDefaults


class Lgm_MagEphemInfo(Lgm_MagEphemInfo):
    """
    LanlGeoMag class for holding Mag Ephem info needed by all models

    @author: Brian Larsen
    @organization: LANL
    @contact: balarsen@lanl.gov

    @version: V1: 19-Jan-2011 (BAL)
    """
    def __init__(self, MaxPitchAngles, Verbosity=0):
        """
        Set the default values from Lgm
        """
        Lgm_InitMagEphemInfoDefaults(pointer(self), MaxPitchAngles, Verbosity)
