#include <stdio.h>
#include <stdlib.h>
#include <strings.h>
#include <string.h>
#include <ctype.h>


int NumberOfColumns( char *String ){
    int n;
    /*
     *  strip off trailing non-alpha-numeric characters...
     */
    for (n=strlen(String); n>=0; --n){
	    if ( !isalnum(String[n]) ) {
	        String[n] = '\0';
	    } else {
	        break;
	    }
    }

    n = 0;
    
    if ( strtok( String, " \t" ) == NULL ) return(0);
    else ++n;
    
    while ( strtok( NULL, " \t" ) != NULL ){
	    ++n;
    }

    return( n );
}



int main(){
    char	Line[4098], GaussType, ModelName[50][128];
    double	ModelYear[50];
    char	h1[2048], h2, h3;
    int		nColumns, nModels, n, m, i;
    double	val[50], del;
    double	g[50][14][14], h[50][14][14];
    FILE	*fpin, *fpout;

    for (i=0; i<50; ++i){
        for(n=0; n<13; ++n){
            for(m=0; m<13; ++m){
	    	    g[i][n][m] = h[i][n][m] = 0.0;
	        }
	    }
    }

    // open txt file containing coefficients
//    fpin = fopen("igrf12coeffs.txt", "r");
    fpin = fopen("igrf14coeffs.txt", "r");

    // read off header (two comment lines, two header lines)
    for (int hl=0; hl<4; hl++) {
        fgets(Line, 4096, fpin);
        printf("Line = %s\n", Line);
    }

    // read in a line of data (as opposed to the header -- better indicator of whats really here
    fgets(Line, 4096, fpin);
    printf("Data Line = %s\n", Line);
    nColumns = NumberOfColumns( Line );
    printf("Columns = %d\n", nColumns);


    nModels = nColumns - 4; // there are 3 colums at start defining coeff, plus SV at the end. 
    printf("nModels = %d\n", nModels);

    rewind(fpin);  // rewind to start of filee
    // read off header
    for (int hl=0; hl<3; hl++) {
        fgets(Line, 4096, fpin);
        printf("Line = %s\n", Line);
    }

    fscanf(fpin, "%s %c %c", h1, &h2, &h3);
    for (i=0; i<nModels; ++i){
        fscanf(fpin, "%lf", &ModelYear[i]);
	    printf("ModelYear = %f\n", ModelYear[i]);
    }
    fgets(Line, 128, fpin); /* read off the rest of the line (icluding newline) */


    /*
     * Read in the SV terms as though they were an additional model (they
     * arent, but its convenient to keep track of the coeffs.)
     */
    while ( fscanf(fpin, "%c %d %d", &GaussType, &n, &m) != EOF ){

	    for (i=0; i<nModels+1; ++i){
	        fscanf(fpin, "%lf", &val[i]);
            //printf("val[%d] = %g\n", i, val[i]);
	    }
	    //fscanf(fpin, "%lf", &del);
	    fgets(Line, 128, fpin); /* read off the rest of the line (icluding newline) */

	    printf("Got: %c_%d_%d\n", GaussType, n, m);

	    /*
	     *  dump values to the proper g and h arrays..
	     */
	    for (i=0; i<nModels+1; ++i){

	        if (GaussType == 'g'){
	            g[i][n][m] = val[i];
	        } else {
	            h[i][n][m] = val[i];
	        }

	    }

    }

    fclose(fpin);

    /*
     *   Now dump out the coefficients as C static arrays...
     */
    fpout = fopen("Lgm_IGRF.h", "w");
    fprintf(fpout, "#ifndef LGM_IGRF_H\n");
    fprintf(fpout, "#define LGM_IGRF_H\n");
    fprintf(fpout, "\n");
    fprintf(fpout, "/*\n");
    fprintf(fpout, " *   Lgm_IGRF.h\n");
    fprintf(fpout, " *\n");
    fprintf(fpout, " *   These are static arrays of the IGRF coefficients.\n");
    fprintf(fpout, " *   This file was computer-generated by fmt_igrf.c, which\n");
    fprintf(fpout, " *   reads a table of coefficients and creates the arrays below.\n");
    fprintf(fpout, " *   The indices are such that;\n");
    fprintf(fpout, " *\n");
    fprintf(fpout, " *\n");
    fprintf(fpout, " *                                             m\n");
    fprintf(fpout, " *               IGRF_g[ModelNumber][n][m] = g          for a given model.\n");
    fprintf(fpout, " *                                             n\n");
    fprintf(fpout, " *\n");
    fprintf(fpout, " *\n");
    fprintf(fpout, " *\n");
    fprintf(fpout, " *   Coefficients from: https://www.ngdc.noaa.gov/IAGA/vmod/coeffs/igrf14coeffs.txt\n");
    fprintf(fpout, " *   ( IGRF 14th generation (finalized November 2024) )\n");
    fprintf(fpout, " *\n");
    fprintf(fpout, " */\n");
    fprintf(fpout, "#ifndef M_SQRT_3\n");
    fprintf(fpout, "#define M_SQRT_3        1.7320508075688772935274463415058       /* sqrt(3)        */\n");
    fprintf(fpout, "#endif\n");


    fprintf(fpout, "\nstatic int    IGRF_nModels = %d;\n\n", nModels);
    fprintf(fpout, "static double IGRF_epoch[%d] = {", nModels+1);
    for (i=0; i<nModels; ++i){
        if (i<(nModels-1)){
            fprintf(fpout, " %.1f,", ModelYear[i]);
	} else {
            fprintf(fpout, " %.1f", ModelYear[i]);
	}
	if (i==9) fprintf(fpout, "\n                               ");
    }
    fprintf(fpout, " };\n\n");


    fprintf(fpout, "static double  IGRF_Re                    = 6371.2; // km This is the so-called \"magnetic reference spherical radius\" that is adopted in IGRF modeling\n");
    fprintf(fpout, "static char    IGRF_Model[]               = \"IGRF14\";\n");
    fprintf(fpout, "static char    IGRF_Model_Description[]   = \"14th Generation International Geomagnetic Reference Field\";\n");
    //fprintf(fpout, "static char    IGRF_Model_Reference[]     = \"International Association of Geomagnetism and Aeronomy, Working Group V-MOD. Participating members, Finlay, C. C., Maus, S., Beggan, C. D., Bondar, T. N., Chambodut, A., Chernova, T. A., Chulliat, A., Golovkov, V. P., Hamilton, B., Hamoudi, M., Holme, R., Hulot, G., Kuang, W., Langlais, B., Lesur, V., Lowes, F. J., Lühr, H., Macmillan, S., Mandea, M., McLean, S., Manoj, C., Menvielle, M., Michaelis, I., Olsen, N., Rauberg, J., Rother, M., Sabaka, T. J., Tangborn, A., Tøffner-Clausen, L., Thébault, E., Thomson, A. W. P., Wardinski, I., Wei, Z. and Zvereva, T. I. (2010), International Geomagnetic Reference Field: the eleventh generation. Geophysical Journal International, 183: 1216–1230. doi: 10.1111/j.1365-246X.2010.04804.x\";\n");
    fprintf(fpout, "static char    IGRF_Model_Reference[]     = \"International Association of Geomagnetism and Aeronomy, Working Group V-MOD. Alken, P., Thébault, E., Beggan, C.D. et al. International Geomagnetic Reference Field: the thirteenth generation. Earth Planets Space 73, 49 (2021). doi: 10.1186/s40623-020-01288-x\";\n");
    fprintf(fpout, "\n");



    for (i=0; i<nModels; ++i){
    	if (i==0) {
            fprintf(fpout, "static double IGRF_g[%d][14][14] = {\n", nModels+1);
	    } 
        for (n=0; n<=13; ++n){
    	    if (n==0) {
	            fprintf(fpout, "  { { ");
	        } else {
	            fprintf(fpout, "    { ");
	        }
            for (m=0; m<=13; ++m){
		        if (m<13){ 
		            fprintf(fpout, "%10.10g, ", g[i][n][m]);
		        } else {
		            fprintf(fpout, "%10.10g ", g[i][n][m]);
		        }
	        }
	        if (n == 5){
	            fprintf(fpout, "},\t/*  IGRF %.1f  */\n", ModelYear[i]);
	        } else if (n<13){ 
	            fprintf(fpout, "},\n");
	        } else {
	            if (i<(nModels-1)){ 
	                fprintf(fpout, "} },\n\n");
		        } else {
	                fprintf(fpout, "} }\n");
		        }
	        }
	    }
    }
    fprintf(fpout, "  };\n");

    // Secular variation coeffs for g
    fprintf(fpout, "\n");
    fprintf(fpout, "static double IGRF_g_SV[14][14] = {\n");
    for (n=0; n<=13; ++n){
	    fprintf(fpout, "    { ");
        for (m=0; m<=13; ++m){
		    if (m<13){ 
		        fprintf(fpout, "%10.10g, ", g[i][n][m]);
		    } else {
		        fprintf(fpout, "%10.10g ", g[i][n][m]);
		    }
	    }
	    if (n == 5){
	        fprintf(fpout, "},\t/*  Secular Variation Terms for IGRF %.1f  */\n", ModelYear[nModels-1]);
	    } else if (n<13){ 
	        fprintf(fpout, "},\n");
	    } else {
	        fprintf(fpout, "}\n");
	    }
	}
    fprintf(fpout, "  };\n");

    for (i=0; i<nModels; ++i){
    	if (i==0) {
            fprintf(fpout, "\n\nstatic double IGRF_h[%d][14][14] = {\n", nModels+1);
	} 
        for (n=0; n<=13; ++n){
    	    if (n==0) {
	        fprintf(fpout, "  { { ");
	    } else {
	        fprintf(fpout, "    { ");
	    }
            for (m=0; m<=13; ++m){


		if (m<13){ 
		    fprintf(fpout, "%10.10g, ", h[i][n][m]);
		} else {
		    fprintf(fpout, "%10.10g ", h[i][n][m]);
		}


	    }
	    if (n == 5){
	        fprintf(fpout, "},\t/*  IGRF %.1f  */\n", ModelYear[i]);
	    } else if (n<13){ 
	        fprintf(fpout, "},\n");
	    } else {
	        if (i<(nModels-1)){ 
	            fprintf(fpout, "} },\n\n");
		} else {
	            fprintf(fpout, "} }\n");
		}
	    }
	}
    }
    fprintf(fpout, "  };\n");

    // Secular variation coeffs for h
    fprintf(fpout, "\n");
    fprintf(fpout, "static double IGRF_h_SV[14][14] = {\n");
    for (n=0; n<=13; ++n){
	    fprintf(fpout, "    { ");
        for (m=0; m<=13; ++m){
		    if (m<13){ 
		        fprintf(fpout, "%10.10g, ", h[i][n][m]);
		    } else {
		        fprintf(fpout, "%10.10g ", h[i][n][m]);
		    }
	    }
	    if (n == 5){
	        fprintf(fpout, "},\t/*  Secular Variation Terms for IGRF %.1f  */\n", ModelYear[nModels-1]);
	    } else if (n<13){ 
	        fprintf(fpout, "},\n");
	    } else {
	        fprintf(fpout, "}\n");
	    }
	}
    fprintf(fpout, "  };\n");

    fprintf(fpout, "\n\n#endif\n");

   fclose(fpout);

}
