#!/usr/bin/env python
import datetime
import numpy as np
import matplotlib
matplotlib.use('Cairo')
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import matplotlib.mlab as mlab


#f = open('/tmp/workfile', 'r')
#

f = open( "SUN.dat", "r" )
a = f.readlines( )
f.close()

line  = ' '
nPnts = 0
Data = np.zeros([12, len(a)], dtype=float)

for line in a:
    cols = line.split(',')
    print cols
    if ( len(cols) == 12 ):
        n = len(cols)
        for i in range(n):
                Data[i][nPnts] = float( cols[i] )
        nPnts = nPnts + 1
                




#plt.subplot(411)
#plt.plot( Data[0][:nPnts-1], Data[8][:nPnts-1] )
##plt.plot( Data[0][:nPnts-1], 10*Data[10][:nPnts-1] )
#plt.title('Low Accuracy Method')
#plt.xlabel('Julian Date')
#plt.ylabel(r'$RA_{JPL}-RA_{LGM}$')


    
fig = plt.figure()
fig.suptitle('Differences between JPL and LGM Sun Positions (JPL-LGM)', fontsize=16, fontweight='bold')
fig.subplots_adjust(hspace=0.1)

ax1 = fig.add_subplot(411)
ax1.set_ylabel(r'$\Delta \rm\bf RA$ (arcsec)', fontsize=11, fontweight='bold')
ax1.text(0.95, 0.75, 'Low Accuracy Method', verticalalignment='bottom', horizontalalignment='right', transform=ax1.transAxes, color='green', fontsize=14)
ax1.plot( Data[0][:nPnts-1]-2454100.0, Data[8][:nPnts-1] )

ax2 = fig.add_subplot(412, sharex=ax1)
ax2.set_ylabel(r'$\Delta \rm\bf DEC$ (arcsec)', fontsize=11, fontweight='bold')
ax2.text(0.95, 0.15, 'Low Accuracy Method', verticalalignment='bottom', horizontalalignment='right', transform=ax2.transAxes, color='green', fontsize=14)
ax2.plot( Data[0][:nPnts-1]-2454100.0, Data[9][:nPnts-1] )

ax3 = fig.add_subplot(413, sharex=ax1)
ax3.set_ylabel(r'$\Delta \rm\bf RA$ (arcsec)', fontsize=11, fontweight='bold')
ax3.text(0.95, 0.15, 'High Accuracy Method', verticalalignment='bottom', horizontalalignment='right', transform=ax3.transAxes, color='blue', fontsize=14)
ax3.plot( Data[0][:nPnts-1]-2454100.0, Data[10][:nPnts-1] )

ax4 = fig.add_subplot(414, sharex=ax1)
ax4.set_ylabel(r'$\Delta \rm\bf DEC$ (arcsec)', fontsize=11, fontweight='bold')
ax4.text(0.95, 0.75, 'High Accuracy Method', verticalalignment='bottom', horizontalalignment='right', transform=ax4.transAxes, color='blue', fontsize=14)
ax4.plot( Data[0][:nPnts-1]-2454100.0, Data[11][:nPnts-1] )
ax4.set_xlabel('Julian Date', fontsize=14, fontweight='bold')


xticklabels = ax1.get_xticklabels()+ax2.get_xticklabels()+ax3.get_xticklabels()
plt.setp(xticklabels, visible=False)

for label in ax4.get_xticklabels() + ax4.get_yticklabels() +ax1.get_yticklabels()+ax2.get_yticklabels()+ax3.get_yticklabels():
      label.set_fontsize(10)


#for tick in fig.axis.get_majorticklines():
#    print "hello"
#      tick.set_linesize(4)


#plt.subplot(413)
#plt.plot( Data[0][:nPnts-1], Data[10][:nPnts-1] )
#plt.title('High Accuracy Method')
#plt.xlabel('Julian Date')
#plt.ylabel(r'$RA_{JPL}-RA_{LGM}$')


#    
#plt.subplot(414)
#plt.plot( Data[0][:nPnts-1], Data[11][:nPnts-1] )
#plt.title('High Accuracy Method')
#plt.xlabel('Julian Date')
#plt.ylabel(r'$DEC_{JPL}-DEC_{LGM}$')
#plt.text(0.95, 0.01, 'colored text in axes coords',
#        verticalalignment='bottom', horizontalalignment='right',
#        transform=ax.transAxes,
#        color='green', fontsize=15)



#plt.show()



plt.savefig('puke.svg', dpi=200)

