       SUBROUTINE LGM_FIELD_T96MOD_MGH(PARMOD,AMDFIN,IYEAR,IDAY,IH,IM,
     * SEC,X,Y,Z,BX,BY,BZ)
       IMPLICIT REAL*8 (A-H,O-Z)
       REAL*8 AMDF(10), PARMOD(10), AMDFIN(10)
       COMMON /GEOPACK1/ST0,CT0,SL0,CL0,CTCL,STCL,CTSL,STSL,SFI,CFI,SPS,
     * CPS,SHI,CHI,HI,PSI,XMUT,A11,A21,A31,A12,A22,A32,A13,A23,A33,DS3,
     * CGST,SGST,BA(6)
       COMMON/CHANGES/ AMDF

       AMDF(1) = AMDFIN(1)
       AMDF(2) = AMDFIN(2)
       AMDF(3) = AMDFIN(3)
       AMDF(4) = AMDFIN(4)
       AMDF(5) = AMDFIN(5)
       AMDF(6) = AMDFIN(6)

       UT=IH+IM/60.D0+SEC/3600.D0

       IF(UT.NE.UT_OLD) THEN
           CALL RECALC (IYEAR,IDAY,IH,IM,IS)
       END IF

       UT_OLD = UT


       CALL T96MOD(1,PARMOD,PSI,X,Y,Z,BX,BY,BZ)

C       WRITE(*,*) 'FIELD_T96MOD: PARMOD(1), PARMOD(2), PARMOD(3), 
C     * PARMOD(4), PSI,X,Y,
C     * Z,BX,BY,BZ =',PARMOD(1), PARMOD(2), PARMOD(3), PARMOD(4), 
C     * PSI,X,Y,Z,BX,BY,BZ 
       CLOSE(10)
       CLOSE(11)
       RETURN


C9      WRITE(*,*) 'WE ARE OUT OF TIME PERIOD FOR THE EVENT'
C       BX=0.0D0
C       BY=0.0D0
C       BZ=0.0D0
C       RETURN
       END               
