#OMP_INC = /usr/local/src/gcc-4.3.1-obj/x86_64-unknown-linux-gnu/libgomp/
CFLAGS    = -O3 -Wall
FFLAGS    =  -fno-automatic 
LIBFILES  =  W.o Tsyg2004.o TS04.o T96mod.o T96_MOD_MGH.o field_t96mod_MGH.o Geopack_2003.o \
             T89.o T87.o Lgm_B_internal.o Lgm_IGRF.o Lgm_CTrans.o Lgm_DateAndTime.o Lgm_Vec.o Lgm_InitMagInfo.o \
             Lgm_Trace.o Lgm_TraceToEarth.o Lgm_TraceToSphericalEarth.o TraceToMinBSurf.o TraceToMinRdotB.o TraceToSMEquat.o MagStep.o   \
             QuadPack.o IntegralInvariant.o TraceToMirrorPoint2.o LFromIBmM.o SbIntegral.o   \
             TraceLine.o QuadPack3.o ComputeLstar.o DriftShell.o quicksort.o AlphaOfK.o Lgm_Quat.o \
             B_FromScatteredData.o Lgm_Octree.o Lgm_SimplifiedMead.o Lgm_Eop.o Lgm_Sgp.o Lgm_SunPosition.o Lgm_Nutation.o
#LIBS      = -L/lib64 -L/usr/lib64 -lm -lgsl -lgslcblas -lg2c 
LIBS      = -L/usr/local/lib -L/lib64 -L/usr/lib64 -lm -lgsl -lgslcblas -lgfortran `perl -MExtUtils::Embed -e ldopts`

CC        = gcc
F90	  = gfortran





# Directories
LGM_INSTALL_DIR  = /usr/local
LGM_EOP_DATA_DIR = /usr/local/share/LanlGeoMag/EopData

# Create Shared Object Library
CFLAGS  = -fPIC -O3 -g -c -Wall -mfpmath=387 -funroll-all-loops -ffast-math -fopenmp -DLGM_EOP_DATA_DIR=$(LGM_EOP_DATA_DIR) `perl -MExtUtils::Embed -e ccopts`
FFLAGS  = -fPIC -O3 -c -fno-automatic 



all   : MagLibrary 

T96mod.o: T96mod.f
	$(F90) $(FFLAGS) -c T96mod.f -o T96mod.o

field_t96mod_MGH.o: field_t96mod_MGH.f
	$(F90) $(FFLAGS) -c field_t96mod_MGH.f -o field_t96mod_MGH.o

Geopack_2003.o: Geopack_2003.f
	$(F90) $(FFLAGS) -c Geopack_2003.f -o Geopack_2003.o




MagLibrary: Makefile $(LIBFILES) $(INCS)
	$(CC) -shared -Wl\,-Bsymbolic\,-soname\,libLanlGeoMag.so.1 -lc -o libLanlGeoMag.so.1.1.1  $(LIBFILES)

InstallLocal: 
	ln -sf  libLanlGeoMag.so.1.1.1 libLanlGeoMag.so.1
	ln -sf  libLanlGeoMag.so.1.1.1 libLanlGeoMag.so

Install: 
	mkdir -p $(LGM_EOP_DATA_DIR)
	sed -e "s+CHANGE_ME+$(LGM_EOP_DATA_DIR)+" EopData/GetEopFiles.in > EopData/GetEopFiles
	chmod +x EopData/GetEopFiles
	cp EopData/GetEopFiles $(LGM_EOP_DATA_DIR)/.
	ln -sf $(LGM_EOP_DATA_DIR)/GetEopFiles /etc/cron.daily/GetEopFiles
	cp libLanlGeoMag.so.1.1.1 $(LGM_INSTALL_DIR)/lib/.
	cp Lgm_CTrans.h $(LGM_INSTALL_DIR)/include/.
	cp Lgm_Eop.h $(LGM_INSTALL_DIR)/include/.
	cp Lgm_FieldIntInfo.h $(LGM_INSTALL_DIR)/include/.
	cp Lgm_IGRF.h $(LGM_INSTALL_DIR)/include/.
	cp Lgm_LstarInfo.h $(LGM_INSTALL_DIR)/include/.
	cp Lgm_MagModelInfo.h $(LGM_INSTALL_DIR)/include/.
	cp Lgm_Octree.h $(LGM_INSTALL_DIR)/include/.
	cp Lgm_Quat.h $(LGM_INSTALL_DIR)/include/.
	cp Lgm_Sgp.h $(LGM_INSTALL_DIR)/include/.
	cp Lgm_Vec.h $(LGM_INSTALL_DIR)/include/.
	cp Lgm_WGS84.h $(LGM_INSTALL_DIR)/include/.
	cp QuadPack.h $(LGM_INSTALL_DIR)/include/.
	mkdir -p $(LGM_INSTALL_DIR)/lib/pkgconfig
	cp lgm.pc $(LGM_INSTALL_DIR)/lib/pkgconfig/.
	ln -sf  $(LGM_INSTALL_DIR)/lib/libLanlGeoMag.so.1.1.1 $(LGM_INSTALL_DIR)/lib/libLanlGeoMag.so.1
	ln -sf  $(LGM_INSTALL_DIR)/lib/libLanlGeoMag.so.1.1.1 $(LGM_INSTALL_DIR)/lib/libLanlGeoMag.so
	ldconfig -n $(LGM_INSTALL_DIR)/lib

clean :
	rm libLanlGeoMag.so.1.1.1 *.o 
	rm EopData/GetEopFiles
	rm /etc/cron.daily/GetEopFiles
