"""
Lgm_MagModelInfo module, this contains the necessary code Mag Model Info

the ugly top part is
Generated by h2py from ../libLanlGeoMag/Lgm/Lgm_MagModelInfo.h
@todo: go through and remove the bits we don't need

@author: Brian Larsen
@organization: LANL
@contact: balarsen@lanl.gov

@version: V1: 20-Dec-2010 (BAL)
"""


###############################################################################
###############################################################################
###############################################################################

# Included from math.h
LGM_ELECTRON_MASS = (9.10938188e-31)
LGM_AMU = (1.660538e-27)
RE = (6378.135e3)
LGM_CC = (2.99792458e8)
LGM_EE = (1.6022e-19)
TRUE = 1
FALSE = 0
LGM_OPEN_IMF = 0
LGM_CLOSED = 1
LGM_OPEN_N_LOBE = 2
LGM_OPEN_S_LOBE = 3
LGM_INSIDE_EARTH = -1
LGM_TARGET_HEIGHT_UNREACHABLE = -2
LGM_MAGSTEP_KMAX = 9
LGM_MAGSTEP_IMAX = (LGM_MAGSTEP_KMAX+1)
LGM_MAGSTEP_JMAX = (LGM_MAGSTEP_KMAX+2)
LGM_MAGSTEP_REDMAX = 1.0e-5
LGM_MAGSTEP_REDMIN = 0.7
LGM_MAGSTEP_SCLMAX = 0.1
LGM_MAGSTEP_SAFE1 = 0.25
LGM_MAGSTEP_SAFE2 = 0.70
DQAGS = 0
DQAGP = 1
DQK21 = 2
LINEAR = 0
LINEAR_DFI = 1
QUADRATIC = 2
QUADRATIC_DFI = 3
NEWTON_INTERP = 4
LGM_CDIP = 0
LGM_EDIP = 1
LGM_IGRF = 2
LGM_MAX_INTERP_PNTS = 10000
LGM_RELATIVE_JUMP_METHOD = 0
LGM_ABSOLUTE_JUMP_METHOD = 1


###############################################################################
###############################################################################
###############################################################################



