#!/usr/bin/env python
import datetime
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import matplotlib.mlab as mlab
from numpy import *


#f = open('/tmp/workfile', 'r')
#

f = open( "EopParams.dat", "r" )
line  = ' '
nPnts = 0
Data = zeros([11, 19000], double)


while line:
    line = f.readline()
    cols = line.split(',')
    if len(cols) == 11:
        n = len(cols)
        for i in range(n):
            Data[i][nPnts] = double( cols[i] )
        nPnts = nPnts + 1
print nPnts






#plt.subplot(411)
#plt.plot( Data[0][:nPnts-1], Data[8][:nPnts-1] )
##plt.plot( Data[0][:nPnts-1], 10*Data[10][:nPnts-1] )
#plt.title('Low Accuracy Method')
#plt.xlabel('Julian Date')
#plt.ylabel(r'$RA_{JPL}-RA_{LGM}$')


    
fig = plt.figure()
fig.suptitle('EOP Values between 19900101 and 20100630', fontsize=32, fontweight='bold')
fig.subplots_adjust(hspace=0.3)

ax3 = fig.add_subplot(311, autoscale_on=True, xlim=(1990,2011) )
ax3.set_ylabel(r'xp, yp (arcsec)', fontsize=24, fontweight='bold')
#ax3.set_xlabel(r'Year', fontsize=28, fontweight='bold')
ax3.plot( Data[3][:nPnts-1], Data[6][:nPnts-1], linewidth=4 )

ax4 = fig.add_subplot(311, autoscale_on=True, xlim=(1990,2011) )
ax4.plot( Data[3][:nPnts-1], Data[7][:nPnts-1], alpha=0.75, linewidth=4, color='red' )



ax5 = fig.add_subplot(312, autoscale_on=True, xlim=(1990,2011) )
ax5.plot( Data[3][:nPnts-1], Data[9][:nPnts-1], linewidth=4, color='orange' )
ax5.set_ylabel(r'dPsi, dEps (arcsec)', fontsize=24, fontweight='bold')

ax6 = fig.add_subplot(312, autoscale_on=True, xlim=(1990,2011) )
ax6.plot( Data[3][:nPnts-1], Data[10][:nPnts-1], linewidth=4, alpha=0.75, color='green' )



ax7 = fig.add_subplot(313, autoscale_on=True, xlim=(1990,2011) )
ax7.plot( Data[3][:nPnts-1], Data[8][:nPnts-1], linewidth=2, color='purple' )
ax7.set_ylabel(r'LOD (sec)', fontsize=24, fontweight='bold')
ax7.set_xlabel(r'Year', fontsize=24, fontweight='bold')


for label in ax3.get_xticklabels()+ax3.get_yticklabels()+ax7.get_xticklabels()+ax7.get_yticklabels()+ax5.get_xticklabels()+ax5.get_yticklabels():
      label.set_fontsize(24)



plt.show()

