"""
Lgm_MagModelInfo module, this contains the necessary code Mag Model Info

the ugly top part is
Generated by h2py from ../libLanlGeoMag/Lgm/Lgm_MagModelInfo.h
@todo: go through and remove the bits we don't need

@author: Brian Larsen
@organization: LANL
@contact: balarsen@lanl.gov

@version: V1: 20-Dec-2010 (BAL)
"""
from ctypes import pointer

from Lgm_Wrap import Lgm_MagModelInfo, Lgm_InitMagInfoDefaults


class Lgm_MagModelInfo(Lgm_MagModelInfo):
    """
    LanlGeoMag class for holing Mag Model infor needed by all models

    @author: Brian Larsen
    @organization: LANL
    @contact: balarsen@lanl.gov

    @version: V1: 22-Dec-2010 (BAL)
    """
    def __init__(self):
        """
        Set the default values from Lgm
        """
        Lgm_InitMagInfoDefaults(pointer(self))
