name: lgm-ci
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  basic-suite:
    runs-on: ubuntu-20.04
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y make gcc g++ autotools-dev autoconf check
        sudo apt-get install -y libgsl-dev libgsl23 gsl-bin libgsl-dbg
        sudo apt-get install -y libhdf5-dev libperl-dev
        gcc --version
        gsl-config --version
    - name: Checkout
      uses: actions/checkout@v2
    - name: compile_test
      run: |
        autoreconf -i
        ./configure
        make
    - name: unit_tests
      run: |
        cd tests
        make check_Sgp4
        make check_CoordTrans
        ./check_Sgp4
        ./check_CoordTrans
