#ifndef LGM_AE8_H
#define LGM_AE8_H

#include <Lgm/Lgm_Vec.h>
#include <Lgm/Lgm_MagModelInfo.h>

/*
 *  Lgm_AE8.h
 *
 *  These are static arrays of the data "MAPS" that are used in the AE8/AP8
 *  radiation belt flux models. This file was computer generated by AE8_Fmt.c
 *  which reads in the raw MAPS used in the fortran code and dumps them in a
 *  more readable format. Note: each array has a leading zero added. This is to
 *  make the arrays compatible with the fortran-stlye arrays starting at index
 *  1 instead, of zero.
 *
 */

#define LGM_AP8MAX 1
#define LGM_AP8MIN 2
#define LGM_AE8MAX 7
#define LGM_AE8MIN 8
#define LGM_INTEGRAL_FLUX     1
#define LGM_DIFFERENTIAL_FLUX 2



void    TRARA1( int DESCR[], int MAP[], double FL, double BB0, double E[], double F[], int N );
double  TRARA2( int MAP[], int IL, int IB, double FISTEP );
double  Lgm_AE8_AP8_Flux( double L, double BB0, int MODEL, int FLUXTYPE, double E1, double E2 );
double  Lgm_AE8_AP8_FluxFromPos( Lgm_Vector *u, int MODEL, int FLUXTYPE, double E1, double E2, Lgm_MagModelInfo *m );




#endif

/*
 *    $Id$
 */
